### ISSUE TITLE
Unable to import .ply file

### ISSUE THREAD

**Issue by akshatd007** [Kiri-Innovation/3dgs-render-blender-addon#4]
After importing a .ply file I get a blender info log as: 

`Python: Traceback (most recent call last):
  File "C:\Users\Imagine\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\gs_render_by_kiri_engine\__init__.py", line 316, in execute
    plyInfo = PlyInfo(ply_import_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Imagine\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\gs_render_by_kiri_engine\__init__.py", line 259, in __init__
    self.loadPly(filepath)
  File "C:\Users\Imagine\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\gs_render_by_kiri_engine\__init__.py", line 276, in loadPly
    self.features_dc[:, 0, 0] = np.asarray(plydata.elements[0]["f_dc_0"])
                                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Imagine\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\gs_render_by_kiri_engine\plyfile.py", line 715, in __getitem__
    return self.data[key]
           ~~~~~~~~~^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\site-packages\numpy\core\memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: no field of name f_dc_0
`

Could anyone tell me why this is happening. Thank you

**Comment by 3pointedit** [comment]
I found that there was an issue with the addon zip folder name in [this thread ](https://github.com/Kiri-Innovation/3dgs-render-blender-addon/issues/2) so try ensuring that the addon name is correct, you may have to decompress, then rename folder and then re-zip it.

**Comment by 3pointedit** [comment]
Also it may depend where the .ply file is from. for example LumaLabsAI allows you to down load a simple point cloud as a .ply but if you choose to download a Splatt file from them, you get a  proper GS .ply which imports fine
