### ISSUE TITLE
Error on clicking "Enable Eevee"

### ISSUE THREAD

**Issue by wjohnson-lcs** [Kiri-Innovation/3dgs-render-blender-addon#8]
I installed the add-on via the Preferences Add-On screen. There is a button that says "Enable Eevee". When I click this button, I receive a popup screen that says:
Report: Error
Python: Traceback (most recent call last):
  File "/Users/Walter/Library/Application Support/Blender/3.6/scripts/addons/gs_render_by_kiri_engine/__init__.py", line 785, in invoke
    return self.execute(context)
  File "/Users/Walter/Library/Application Support/Blender/3.6/scripts/addons/gs_render_by_kiri_engine/__init__.py", line 781, in execute
    bpy.context.scene.render.engine = 'BLENDER_EEVEE_NEXT'
TypeError: bpy_struct: item.attr = val: enum "BLENDER_EEVEE_NEXT" not found in ('BLENDER_EEVEE', 'BLENDER_WORKBENCH', 'CYCLES')

And I cannot use the add-on.

**Comment by wjohnson-lcs** [comment]
This is the error if you have version 3.6.x rather than 4.2.x
